# -*- coding: utf-8 -*-
"""코드인 3주차 문제.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Zf5cHm6fqeS-tnAmrf0I4j8V0plgTyb
"""

sentence = input('문장 입력:') # 문장 입력 받기
words = sentence.split( ) # 공백 기준으로 문장을 단어로 나누기
for word in words: # 단어들 안에 하나의 단어
  if word == word[::-1]: # 단어가 거꾸로 해도 같을 때
    print (f'{word}') # 그 단어를 출력하세요

id = input('아이디:') # 아이디 입력 받기
pw = str(input('비밀번호:')) # 비번 입력 받기
pwc = '*' * len(pw) # 비번 개수 x *
print (pwc) # 비번 가린채로 출력

word = input('단어 입력:') #단어 입력 받기
print (f'{word[::-1]}') # 단어 거꾸로 뒤집은 거 출력하기

word = input('단어 입력:') # 단어 입력 받기
for vowels in word: # 그 단어 안에 있는 글자
  if vowels in 'aeiou': # aeiou 안에 글자가 포함된다면
    print (vowels,end='') # 글자들 출력

number = int(input('숫자를 입력:')) # 숫자 입력받기
for i in range(1, number+1): # 1부터 숫자까지 계단식으로 * 개수 입력
  print('*' * i) # 별 출력
for l in range(number-1,0,-1): # 숫자-1에서 1까지 계단식으로 * 개수 입력, 큰 숫자에서 작은 숫자로 내려갈때는 뒤에 -1 붙이기!!!!
  print('*' * l) # 출력^^
