# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WzDBML9QpXffRt2qYXQe5DZ7alIakgrQ
"""

# 원래 계획
# 나사에서 api 받아서 데이터 받기
# 천체별 적경을 받기
#
# 천체끼리 일직선상에 있게 되는 주기 구하기
# 태양계 행성 내에 천체 별로 코드를 부여하여 입력 받은 천체 종류와 수에 따라 결과값 반환.
# 반환은 행성들의 순서와 가장 가까운 예정일 구하기.
#

import requests
import pandas as pd
import numpy as np
from io import StringIO

# =========================
# 1. 행성 코드: JPL Horizons COMMAND ID
# =========================

PLANETS = {
    "수성": {"id": "199", "period": 87.969},
    "금성": {"id": "299", "period": 224.701},
    "지구": {"id": "399", "period": 365.256},
    "화성": {"id": "499", "period": 686.980},
    "목성": {"id": "599", "period": 4332.589},
    "토성": {"id": "699", "period": 10759.22},
    "천왕성": {"id": "799", "period": 30685.4},
    "해왕성": {"id": "899", "period": 60189.0},
}

API_URL = "https://ssd.jpl.nasa.gov/api/horizons.api"


# =========================
# 2. 회합주기 계산
# =========================

def synodic_period(body1, body2):
    """
    두 천체의 공전주기를 이용해 회합주기 계산
    S = 1 / |1/P1 - 1/P2|
    """
    p1 = PLANETS[body1]["period"]
    p2 = PLANETS[body2]["period"]
    return 1 / abs(1 / p1 - 1 / p2)


# =========================
# 3. NASA/JPL Horizons API에서 적경 가져오기
# =========================

def fetch_ra_from_horizons(planet_name, start_time, stop_time, step_size="1 d"):
    """
    행성의 적경 RA 값을 가져오는 함수
    CENTER='500@10'은 태양 중심 기준
    ANG_FORMAT='DEG'는 각도를 도 단위로 받기 위한 설정
    """
    command_id = PLANETS[planet_name]["id"]

    params = {
        "format": "text",
        "COMMAND": command_id,
        "CENTER": "500@10",
        "EPHEM_TYPE": "OBSERVER",
        "MAKE_EPHEM": "YES",
        "OBJ_DATA": "NO",
        "QUANTITIES": "1",
        "CSV_FORMAT": "YES",
        "ANG_FORMAT": "DEG",
        "REF_SYSTEM": "ICRF",
        "START_TIME": start_time,
        "STOP_TIME": stop_time,
        "STEP_SIZE": step_size,
        "TIME_DIGITS": "SECONDS",
    }

    response = requests.get(API_URL, params=params, timeout=30)
    response.raise_for_status()
    text = response.text

    if "$$SOE" not in text or "$$EOE" not in text:
        raise ValueError(f"{planet_name} 데이터를 읽지 못했습니다.\n{text[:1000]}")

    table_text = text.split("$$SOE")[1].split("$$EOE")[0].strip()

    raw = pd.read_csv(StringIO(table_text), header=None)
    raw.columns = [f"col{i}" for i in range(raw.shape[1])]

    raw["datetime"] = pd.to_datetime(
        raw["col0"].astype(str).str.strip(),
        errors="coerce"
    )

    # 날짜 다음에 나오는 0~360 범위의 숫자열을 RA 열로 추정
    ra_col = None
    for col in raw.columns[1:]:
        nums = pd.to_numeric(raw[col], errors="coerce")
        if nums.notna().sum() > 0:
            ratio = nums.dropna().between(0, 360).mean()
            if ratio > 0.8:
                ra_col = col
                break

    if ra_col is None:
        raise ValueError(f"{planet_name}의 적경 RA 열을 찾지 못했습니다.")

    result = pd.DataFrame({
        "datetime": raw["datetime"],
        planet_name: pd.to_numeric(raw[ra_col], errors="coerce")
    }).dropna()

    return result


# =========================
# 4. 적경 순서와 모임 정도 계산
# =========================

def circular_spread_and_order(ra_values, names):
    """
    적경은 0~360도 원형 값이다.
    따라서 단순히 max - min을 쓰면 안 된다.

    예:
    359도와 1도는 실제로 358도 차이가 아니라 2도 차이다.
    """
    ra_values = np.array(ra_values, dtype=float) % 360
    names = np.array(names)

    order = np.argsort(ra_values)
    sorted_ra = ra_values[order]
    sorted_names = names[order]

    gaps = np.diff(sorted_ra)
    wrap_gap = 360 - sorted_ra[-1] + sorted_ra[0]
    gaps = np.append(gaps, wrap_gap)

    max_gap_index = np.argmax(gaps)
    spread = 360 - gaps[max_gap_index]

    start = (max_gap_index + 1) % len(sorted_ra)

    ordered_names = list(np.roll(sorted_names, -start))
    ordered_ra = list(np.roll(sorted_ra, -start))

    return spread, ordered_names, ordered_ra


# =========================
# 5. 가장 가까운 정렬 시각 찾기
# =========================

def find_closest_alignment(input_planets, start="2026-01-01", years=80):
    """
    입력한 행성들의 적경이 가장 비슷해지는 시각을 찾는다.

    1차 탐색: 일 단위
    2차 탐색: 가장 좋은 날짜 주변을 시간 단위로 다시 탐색
    """
    input_planets = [p.strip() for p in input_planets]

    for p in input_planets:
        if p not in PLANETS:
            raise ValueError(f"지원하지 않는 천체입니다: {p}")

    start_dt = pd.to_datetime(start)
    stop_dt = start_dt + pd.DateOffset(years=years)

    start_str = start_dt.strftime("%Y-%b-%d")
    stop_str = stop_dt.strftime("%Y-%b-%d")

    print("1차 탐색: 일 단위 데이터 수집 중...")

    dfs = []

    for planet in input_planets:
        df = fetch_ra_from_horizons(
            planet,
            start_time=start_str,
            stop_time=stop_str,
            step_size="1 d"
        )
        dfs.append(df)

    merged = dfs[0]

    for df in dfs[1:]:
        merged = pd.merge(merged, df, on="datetime", how="inner")

    spreads = []
    orders = []
    ordered_ras = []

    for _, row in merged.iterrows():
        ra_values = [row[p] for p in input_planets]
        spread, order, order_ra = circular_spread_and_order(
            ra_values,
            input_planets
        )

        spreads.append(spread)
        orders.append(order)
        ordered_ras.append(order_ra)

    merged["spread_deg"] = spreads
    merged["order"] = orders
    merged["ordered_ra"] = ordered_ras

    best_day = merged.loc[merged["spread_deg"].idxmin()]
    best_time = best_day["datetime"]

    print("2차 탐색: 가장 좋은 날짜 주변을 시간 단위로 재탐색 중...")

    refine_start = best_time - pd.Timedelta(days=3)
    refine_stop = best_time + pd.Timedelta(days=3)

    dfs = []

    for planet in input_planets:
        df = fetch_ra_from_horizons(
            planet,
            start_time=refine_start.strftime("%Y-%b-%d %H:%M:%S"),
            stop_time=refine_stop.strftime("%Y-%b-%d %H:%M:%S"),
            step_size="1 h"
        )
        dfs.append(df)

    refined = dfs[0]

    for df in dfs[1:]:
        refined = pd.merge(refined, df, on="datetime", how="inner")

    spreads = []
    orders = []
    ordered_ras = []

    for _, row in refined.iterrows():
        ra_values = [row[p] for p in input_planets]
        spread, order, order_ra = circular_spread_and_order(
            ra_values,
            input_planets
        )

        spreads.append(spread)
        orders.append(order)
        ordered_ras.append(order_ra)

    refined["spread_deg"] = spreads
    refined["order"] = orders
    refined["ordered_ra"] = ordered_ras

    best = refined.loc[refined["spread_deg"].idxmin()]

    result = {
        "입력": input_planets,
        "행성_순서": best["order"],
        "가장_가까운_일시_UTC": best["datetime"],
        "적경_도": dict(zip(best["order"], np.round(best["ordered_ra"], 4))),
        "모임_각도폭_도": round(best["spread_deg"], 4)
    }

    return result


# =========================
# 6. 실행 예시
# =========================

planets = ["지구", "천왕성", "목성", "화성"]

result = find_closest_alignment(
    planets,
    start="2026-01-01",
    years=80
)

print()
print("===== 결과 =====")
print("입력:", ", ".join(result["입력"]))
print("결과:", ", ".join(result["행성_순서"]))
print("가장 가까운 일시 UTC:", result["가장_가까운_일시_UTC"])

print("적경:")
for planet, ra in result["적경_도"].items():
    print(f"  {planet}: {ra}도")

print("행성들이 차지하는 최소 각도폭:", result["모임_각도폭_도"], "도")