# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12jDbkDAbsjGOcML3BtW3v90JKEyqWCeR
"""

import requests
import pandas as pd
import numpy as np
from io import StringIO

HORIZONS_API_URL = "https://ssd.jpl.nasa.gov/api/horizons.api"

PLANET_INFO = {
    "수성": {"horizons_id": "199", "orbital_period_days": 87.969},
    "금성": {"horizons_id": "299", "orbital_period_days": 224.701},
    "지구": {"horizons_id": "399", "orbital_period_days": 365.256},
    "화성": {"horizons_id": "499", "orbital_period_days": 686.980},
    "목성": {"horizons_id": "599", "orbital_period_days": 4332.589},
    "토성": {"horizons_id": "699", "orbital_period_days": 10759.22},
    "천왕성": {"horizons_id": "799", "orbital_period_days": 30685.4},
    "해왕성": {"horizons_id": "899", "orbital_period_days": 60189.0},
}

def get_horizons_text(
    planet_name,
    start_time,
    stop_time,
    step_size="1 d",
    center_code="500@10"
):
    planet_id = PLANET_INFO[planet_name]["horizons_id"]

    request_params = {
        "format": "text",
        "COMMAND": f"'{planet_id}'",
        "OBJ_DATA": "'NO'",
        "MAKE_EPHEM": "'YES'",
        "EPHEM_TYPE": "'OBSERVER'",
        "CENTER": f"'{center_code}'",
        "START_TIME": f"'{start_time}'",
        "STOP_TIME": f"'{stop_time}'",
        "STEP_SIZE": f"'{step_size}'",
        "QUANTITIES": "'1'",
        "CSV_FORMAT": "'YES'",
        "ANG_FORMAT": "'DEG'",
    }

    api_response = requests.get(
        HORIZONS_API_URL,
        params=request_params,
        timeout=30
    )

    print("요청 주소:")
    print(api_response.url)
    print("상태 코드:", api_response.status_code)

    api_response.raise_for_status()

    return api_response.text

def parse_ra_table(horizons_text, planet_name):
    if "$$SOE" not in horizons_text or "$$EOE" not in horizons_text:
        print(horizons_text[:2000])
        raise ValueError("Horizons 데이터 시작/끝 표시를 찾지 못했습니다.")

    table_text = horizons_text.split("$$SOE")[1].split("$$EOE")[0].strip()

    parsed_table = pd.read_csv(StringIO(table_text), header=None)

    # QUANTITIES='1', ANG_FORMAT='DEG', CSV_FORMAT='YES'일 때 보통:
    # 0열: 날짜
    # 1열: Julian Date
    # 2열: 적경 RA
    # 3열: 적위 DEC
    ra_table = parsed_table[[0, 2, 3]].copy()
    ra_table.columns = ["datetime", f"{planet_name}_RA_deg", f"{planet_name}_DEC_deg"]

    ra_table["datetime"] = pd.to_datetime(
        ra_table["datetime"].astype(str).str.strip(),
        errors="coerce"
    )

    ra_table[f"{planet_name}_RA_deg"] = pd.to_numeric(
        ra_table[f"{planet_name}_RA_deg"],
        errors="coerce"
    )

    ra_table[f"{planet_name}_DEC_deg"] = pd.to_numeric(
        ra_table[f"{planet_name}_DEC_deg"],
        errors="coerce"
    )

    ra_table = ra_table.dropna()

    return ra_table

def get_planet_ra_table(
    planet_name,
    start_time,
    stop_time,
    step_size="1 d",
    center_code="500@10"
):
    horizons_text = get_horizons_text(
        planet_name=planet_name,
        start_time=start_time,
        stop_time=stop_time,
        step_size=step_size,
        center_code=center_code
    )

    planet_ra_table = parse_ra_table(
        horizons_text=horizons_text,
        planet_name=planet_name
    )

    return planet_ra_table

def get_multiple_planet_ra_table(
    planet_names,
    start_time,
    stop_time,
    step_size="1 d",
    center_code="500@10"
):
    combined_ra_table = None

    for current_planet_name in planet_names:
        current_planet_ra_table = get_planet_ra_table(
            planet_name=current_planet_name,
            start_time=start_time,
            stop_time=stop_time,
            step_size=step_size,
            center_code=center_code
        )

        current_planet_ra_only = current_planet_ra_table[
            ["datetime", f"{current_planet_name}_RA_deg"]
        ]

        if combined_ra_table is None:
            combined_ra_table = current_planet_ra_only
        else:
            combined_ra_table = pd.merge(
                combined_ra_table,
                current_planet_ra_only,
                on="datetime",
                how="inner"
            )

    return combined_ra_table

def get_ra_order_at_each_time(ra_table, planet_names):
    ordered_result_rows = []

    for row_index, row_data in ra_table.iterrows():
        planet_ra_pairs = []

        for planet_name in planet_names:
            ra_column_name = f"{planet_name}_RA_deg"

            planet_ra_pairs.append({
                "planet": planet_name,
                "ra_deg": row_data[ra_column_name]
            })

        sorted_planet_ra_pairs = sorted(
            planet_ra_pairs,
            key=lambda item: item["ra_deg"]
        )

        ordered_planets = [
            item["planet"] for item in sorted_planet_ra_pairs
        ]

        ordered_ra_values = [
            item["ra_deg"] for item in sorted_planet_ra_pairs
        ]

        ordered_result_rows.append({
            "datetime": row_data["datetime"],
            "planet_order": ordered_planets,
            "ra_order": ordered_ra_values
        })

    ordered_result_table = pd.DataFrame(ordered_result_rows)

    return ordered_result_table

selected_planet_names = ["지구", "화성", "목성", "천왕성"]

all_planet_ra_table = get_multiple_planet_ra_table(
    planet_names=selected_planet_names,
    start_time="2026-Jan-01",
    stop_time="2026-Jan-10",
    step_size="1 d",
    center_code="500@10"
)

all_planet_ra_table.head()

def calculate_circular_ra_spread(ra_values):
    """
    적경은 0~360도 원형 값이므로,
    단순 max-min이 아니라 원형 기준 최소 폭을 계산한다.
    """
    sorted_ra_values = np.sort(np.array(ra_values) % 360)

    gaps_between_ra = np.diff(sorted_ra_values)
    wrap_around_gap = 360 - sorted_ra_values[-1] + sorted_ra_values[0]

    all_gaps = np.append(gaps_between_ra, wrap_around_gap)

    largest_empty_gap = np.max(all_gaps)
    minimum_containing_spread = 360 - largest_empty_gap

    return minimum_containing_spread

def find_closest_ra_alignment(ra_table, planet_names):
    alignment_result_rows = []

    for row_index, row_data in ra_table.iterrows():
        current_ra_values = []

        for planet_name in planet_names:
            ra_column_name = f"{planet_name}_RA_deg"
            current_ra_values.append(row_data[ra_column_name])

        current_spread = calculate_circular_ra_spread(current_ra_values)

        planet_ra_pairs = []

        for planet_name in planet_names:
            ra_column_name = f"{planet_name}_RA_deg"

            planet_ra_pairs.append({
                "planet": planet_name,
                "ra_deg": row_data[ra_column_name]
            })

        sorted_planet_ra_pairs = sorted(
            planet_ra_pairs,
            key=lambda item: item["ra_deg"]
        )

        ordered_planets = [item["planet"] for item in sorted_planet_ra_pairs]
        ordered_ra_values = [item["ra_deg"] for item in sorted_planet_ra_pairs]

        alignment_result_rows.append({
            "datetime": row_data["datetime"],
            "planet_order": ordered_planets,
            "ra_order": ordered_ra_values,
            "spread_deg": current_spread
        })

    alignment_result_table = pd.DataFrame(alignment_result_rows)

    best_alignment_row = alignment_result_table.loc[
        alignment_result_table["spread_deg"].idxmin()
    ]

    return best_alignment_row, alignment_result_table

best_alignment_row, alignment_result_table = find_closest_ra_alignment(
    ra_table=all_planet_ra_table,
    planet_names=selected_planet_names
)

print("===== 결과 =====")
print("행성 순서:", " → ".join(best_alignment_row["planet_order"]))
print("가장 가까운 일시:", best_alignment_row["datetime"])
print("행성들이 차지하는 최소 적경 폭:", round(best_alignment_row["spread_deg"], 4), "도")

print()
print("적경:")
for planet_name, ra_value in zip(
    best_alignment_row["planet_order"],
    best_alignment_row["ra_order"]
):
    print(f"{planet_name}: {round(ra_value, 4)}도")

print(all_planet_ra_table.columns)
print(selected_planet_names)

def find_closest_ra_alignment(ra_table, planet_names):
    # 열 이름 공백 제거
    cleaned_ra_table = ra_table.copy()
    cleaned_ra_table.columns = cleaned_ra_table.columns.astype(str).str.strip()

    cleaned_planet_names = [planet.strip() for planet in planet_names]

    print("현재 표의 열 이름:")
    print(list(cleaned_ra_table.columns))

    print()
    print("찾으려는 RA 열 이름:")
    expected_ra_columns = [f"{planet}_RA_deg" for planet in cleaned_planet_names]
    print(expected_ra_columns)

    missing_columns = [
        column_name for column_name in expected_ra_columns
        if column_name not in cleaned_ra_table.columns
    ]

    if missing_columns:
        raise KeyError(
            "다음 RA 열을 찾지 못했습니다: "
            + ", ".join(missing_columns)
            + "\n현재 존재하는 열: "
            + ", ".join(cleaned_ra_table.columns)
        )

    alignment_result_rows = []

    for row_index, row_data in cleaned_ra_table.iterrows():
        current_ra_values = []

        for planet_name in cleaned_planet_names:
            ra_column_name = f"{planet_name}_RA_deg"
            current_ra_values.append(row_data[ra_column_name])

        current_spread = calculate_circular_ra_spread(current_ra_values)

        planet_ra_pairs = []

        for planet_name in cleaned_planet_names:
            ra_column_name = f"{planet_name}_RA_deg"

            planet_ra_pairs.append({
                "planet": planet_name,
                "ra_deg": row_data[ra_column_name]
            })

        sorted_planet_ra_pairs = sorted(
            planet_ra_pairs,
            key=lambda item: item["ra_deg"]
        )

        ordered_planets = [item["planet"] for item in sorted_planet_ra_pairs]
        ordered_ra_values = [item["ra_deg"] for item in sorted_planet_ra_pairs]

        alignment_result_rows.append({
            "datetime": row_data["datetime"],
            "planet_order": ordered_planets,
            "ra_order": ordered_ra_values,
            "spread_deg": current_spread
        })

    alignment_result_table = pd.DataFrame(alignment_result_rows)

    best_alignment_row = alignment_result_table.loc[
        alignment_result_table["spread_deg"].idxmin()
    ]

    return best_alignment_row, alignment_result_table

best_alignment_row, alignment_result_table = find_closest_ra_alignment(
    ra_table=all_planet_ra_table,
    planet_names=selected_planet_names
)

print("===== 결과 =====")
print("행성 순서:", " → ".join(best_alignment_row["planet_order"]))
print("가장 가까운 일시:", best_alignment_row["datetime"])
print("행성들이 차지하는 최소 적경 폭:", round(best_alignment_row["spread_deg"], 4), "도")

print()
print("적경:")
for planet_name, ra_value in zip(
    best_alignment_row["planet_order"],
    best_alignment_row["ra_order"]
):
    print(f"{planet_name}: {round(ra_value, 4)}도")

selected_planet_names = ["지구", "화성", "목성", "천왕성"]

all_planet_ra_table = get_multiple_planet_ra_table(
    planet_names=selected_planet_names,
    start_time="2026-Jan-01",
    stop_time="2026-Jan-10",
    step_size="1 d",
    center_code="500@10"
)

print(all_planet_ra_table.head())
print(all_planet_ra_table.columns)